### ISSUE TITLE
Secure Connection error

### ISSUE THREAD

**Issue by daxfrancis** [statianzo/Fleck#154] opened 2015-12-09 09:16 UTC
![image](https://cloud.githubusercontent.com/assets/14291232/11681203/74abe5dc-9e83-11e5-8c08-361b599d6590.png)

please help me to solve this error.

my code sample in server is

 var server = new WebSocketServer("wss://127.0.0.1:9393");
            server.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate2("mycert.pfx", "pwd");

**Comment by statianzo** [comment] 2015-12-09 16:59
Duplicate of #148. Continue in that issue.

**Closed by statianzo** 2015-12-09 16:59 UTC
